/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Actinver.nuevo;

import java.io.IOException;
import java.net.URISyntaxException;

/**
 *
 * @author mrchu
 */
public class Inicio extends javax.swing.JFrame {

    public ApiKey key = new ApiKey();
    public JavaVersion javaV = new JavaVersion();
    
    
    public Inicio() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        API = new javax.swing.JButton();
        Series = new javax.swing.JButton();
        Java = new javax.swing.JButton();
        Status1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideBar.setBackground(new java.awt.Color(4, 30, 66));

        API.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        API.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Actinver/nuevo/imagenes/APIKEY.png"))); // NOI18N
        API.setText("Agregar API Key");
        API.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        API.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APIActionPerformed(evt);
            }
        });

        Series.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Series.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Actinver/nuevo/imagenes/descarga.png"))); // NOI18N
        Series.setText("Descargar Series");
        Series.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Series.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Series.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeriesActionPerformed(evt);
            }
        });

        Java.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Java.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Actinver/nuevo/imagenes/java.png"))); // NOI18N
        Java.setText("Java Version");
        Java.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaActionPerformed(evt);
            }
        });

        Status1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Status1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Actinver/nuevo/imagenes/tokens.png"))); // NOI18N
        Status1.setText("API Status");
        Status1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Actinver/nuevo/imagenes/logo_actinverEscalado.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(API, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Series, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Java, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(API, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Series, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Status1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Java, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void APIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APIActionPerformed
        Panel.removeAll();
    	Panel.add(key);
        Panel.revalidate();
        Panel.repaint();
        Panel.setVisible(true);
        
    }//GEN-LAST:event_APIActionPerformed

    private void SeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeriesActionPerformed
     
        Panel.removeAll();
        descarga download = new descarga(key.llave);
    	Panel.add(download);
        Panel.revalidate();
        Panel.repaint();
        Panel.setVisible(true);
    }//GEN-LAST:event_SeriesActionPerformed

    private void JavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaActionPerformed
        Panel.removeAll();
        Panel.add(javaV);
        Panel.revalidate();
        Panel.repaint();
        Panel.setVisible(true);
    }//GEN-LAST:event_JavaActionPerformed

    private void Status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status1ActionPerformed
         Panel.removeAll(); 
        ApiStatus status= new ApiStatus(key.llave);
        Panel.add(status);
        Panel.revalidate();
        Panel.repaint();
        Panel.setVisible(true);
    }//GEN-LAST:event_Status1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
                try{
                    java.net.URI uri = new java.net.URI("https://www.actinver.com/web/actinver/");
                    desktop.browse(uri);

                }catch(URISyntaxException | IOException ex){}
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton API;
    private javax.swing.JButton Java;
    public javax.swing.JPanel Panel;
    private javax.swing.JButton Series;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton Status1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
