/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.actinverflights;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.TransferHandler;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 *
 * @author mrchu
 */
public class Vuelos extends javax.swing.JPanel {

    public String rutaDriver = "";
    public String rutaInput = "";
    public String savPath = "";
    public int idNavegador = 0;

    public String getRutaDriver() {
        return rutaDriver;
    }

    public void setRutaDriver(String rutaDriver) {
        this.rutaDriver = rutaDriver;
    }

    public String getSavPath() {
        return savPath;
    }

    public void setSavPath(String savPath) {
        this.savPath = savPath;
    }

    public int getIdNavegador() {
        return idNavegador;
    }

    public void setIdNavegador(int idNavegador) {
        this.idNavegador = idNavegador;
    }

    /**
     * Creates new form vuelos
     */
    public Vuelos() {
        initComponents();
        modifyLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DragNdrop = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 51));
        setMaximumSize(new java.awt.Dimension(32767, 299));
        setMinimumSize(new java.awt.Dimension(0, 299));
        setPreferredSize(new java.awt.Dimension(785, 315));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona o arrastra un archivo para la búsqueda");

        DragNdrop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Examinar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Elige una ruta para guardar los datos de la búsqueda");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("DESCARGAR DATOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DragNdrop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(DragNdrop, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(11, 11, 11)
                .addComponent(jLabel8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        this.savPath = archivo.getAbsolutePath();
        jTextField1.setText(this.savPath);
        System.out.println();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ChooseBrowser.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        rutaInput = archivo.getAbsolutePath();
        jTextField2.setText(rutaInput);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            buscar();
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void modifyLabel() {
        TransferHandler th = new TransferHandler() {

            @Override
            public boolean canImport(JComponent comp, DataFlavor[] transferFlavors) {
                return true;
            }

            @Override
            public boolean importData(JComponent comp, Transferable t) {

                try {
                    List<File> file = (List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);
                    rutaInput = file.get(0).getAbsolutePath();
                    jTextField2.setText(rutaInput);
                } catch (UnsupportedFlavorException | IOException ex) {
                    Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
                }
                return false;
            }

        };
        DragNdrop.setTransferHandler(th);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DragNdrop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public void buscar() throws IOException, InterruptedException {
        WebDriver driver = null;
        ErrorWindow window = new ErrorWindow();
        window.getjLabel1().setText("<html><p>Parece que el driver no corresponde al navegador seleccionado o el navegador seleccionado no se encuentra instalado en el equipo</p></html>");
        try {
            if (rutaDriver.equals("")) {
                window.setVisible(true);
            } else {
                if (this.idNavegador == 1) {
                    System.setProperty("webdriver.edge.driver", rutaDriver);
                    driver = new EdgeDriver();
                }
                if (this.idNavegador == 2) {
                    System.setProperty("webdriver.gecko.driver", rutaDriver);
                    driver = new FirefoxDriver(); 
                            
                }
                if (this.idNavegador == 3) {
                    System.setProperty("webdriver.chrome.driver", rutaDriver);
                    driver = new ChromeDriver();
                }
            }

        } catch (Exception e) {
            window.setVisible(true);
        }

        driver.get("https://www.google.com/travel/flights?tfs=CBwQARoaagwIAhIIL20vMDRzcWoSCjIwMjEtMDQtMjYaGhIKMjAyMS0wNC0zMHIMCAISCC9tLzA0c3FqcAGCAQsI____________AUABSAGYAQE&hl=es");
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        WebDriverWait wait = new WebDriverWait(driver, 10);

        // SELECCIONAMOS LA CIUDAD DE PARTIDA
        List<List<String>> data = getData();
        List<String> citiespartidas = data.get(0);

        // SELECCIONAMOS LA CIUDAD DE LLEGADA
        List<String> citiesLlegada = data.get(1);
        
        //SELECCIONAMOS LOS NUMEROS DE PASAJEROS
        List<String> pasajeros = data.get(2);
        
        //SELECCIONAMOS LAS CLASES DE LOS VUELOS
        List<String> clasesVuelos = data.get(3);
        
        
        for(int i = 0;i <= pasajeros.size();i++){
            clickDatos(driver,wait,pasajeros.get(i),clasesVuelos.get(i));
        }

        /*
        //Rellenamos los inputs con las ciudades
         WebElement inputPartida = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@class='II2One j0Ppje zmMKJ LbIaRd']")));
            //System.out.println("Este es el input: " + citiespartidas.get(i));
            inputPartida.click();
            inputPartida.clear();
            inputPartida.sendKeys("Guadalajara");
        */
       

    }
    public void clickDatos(WebDriver driver,WebDriverWait wait,String pasajeros,String clase){
        // SELECCIONAMOS LA CLASE
        WebElement claseButton = driver.findElements(By.xpath("//button[@class='VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-INsAgc VfPpkd-LgbsSe-OWXEXe-dgl2Hf Rj2Mlf OLiIxf PDpWxe BobFtf']")).get(2);
        claseButton.click();

        WebElement claseOptions = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[@class='A8nfpe yRXJAe iWO5td']")));
        WebElement claseOption = claseOptions.findElement(By.xpath("//li[text()='" + clase + "']"));
        claseOption.click();

        // SELECCIONAMOS EL NUMERO DE PASAJEROS
        //Damos click en el boton pasajeros
        WebElement pasajerosButton = driver.findElements(By.xpath("//button[@class='VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-INsAgc VfPpkd-LgbsSe-OWXEXe-dgl2Hf Rj2Mlf OLiIxf PDpWxe BobFtf']")).get(1);
        pasajerosButton.click();

        //Damos click en el boton de adultos
        WebElement tabla = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//ul[@class='Xdzhob Lxea9c']")));
        WebElement numPasajerosMas = tabla.findElements(By.xpath("//button[@class='VfPpkd-Bz112c-LgbsSe yHy1rc eT1oJ rGF6nb']")).get(1);
        WebElement numPasajerosMenos = tabla.findElements(By.xpath("//button[@class='VfPpkd-Bz112c-LgbsSe yHy1rc eT1oJ rGF6nb']")).get(0);
        
        WebElement numPasajerosSpan = tabla.findElement(By.xpath("//span[@jsname='NnAfwf']"));
        
        //Verificamos si el numero de pasajeros ya es igual al numero de pasajeros que queremos
        if(!numPasajerosSpan.getText().equals(pasajeros)) {

            //Si es menor damos click en más hasta que sea igual
                while (Integer.parseInt(numPasajerosSpan.getText()) < Integer.parseInt(pasajeros)) {
                    numPasajerosMas.click();
                }
            //Si es mayor damos clic en menos hasta que sea igual
                while(Integer.parseInt(numPasajerosSpan.getText()) > Integer.parseInt(pasajeros)) {
                    numPasajerosMenos.click();
                }

        }
        //Damos click en listo
        WebElement listoButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//button[@class='VfPpkd-LgbsSe ksBjEc lKxP2d bRx3h']")));
        listoButton.click();
    }

    public List<List<String>> getData() throws FileNotFoundException, IOException {
        /*
        Regresa la lista de ciudades dependiendo el indice
        ciudades de partida
        ciudades de llegad
        numero de pasajeros
        clase
         */
        BufferedReader archivo = new BufferedReader(new FileReader(rutaInput));
        List<String> ciudadesPartida = new ArrayList<>();
        List<String> ciudadesLlegada = new ArrayList<>();
        List<String> numPasajeros = new ArrayList<>();
        List<String> clase = new ArrayList<>();
        String line = archivo.readLine();
        while (line != null) {
            String[] camposCsv = line.split(",");
            ciudadesPartida.add(camposCsv[0]);
            ciudadesLlegada.add(camposCsv[1]);
            numPasajeros.add(camposCsv[2]);
            clase.add(camposCsv[3]);
            line = archivo.readLine();
        }

        List<List<String>> datos = new ArrayList<>();
        datos.add(ciudadesPartida);
        datos.add(ciudadesLlegada);
        datos.add(numPasajeros);
        datos.add(clase);        

        return datos;

    }

}
